---
# Set dependencies variables
- name: Set OS-sepcific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Update apt cache [Ubuntu]
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

# Install dependencies
- name: Install dependencies
  package:
    name: "{{ packages }}"
    state: present

- name: Create venv and install pip
  pip:
    name: pip
    version: '{{ pip_version }}'
    virtualenv: '{{ pyluks_venv }}'
    virtualenv_command: python3 -m virtualenv
  
- name: Install pyluks in venv 
  pip:
    name: '{{ pyluks_package_name }}' 
    version: '{{ pyluks_version }}'
    virtualenv: '{{ pyluks_venv }}'
