---
- name: Create user luksctl_api
  user:
    name: luksctl_api
    shell: '/bin/bash'

- name: Set luksctl_api user permissions in sudoers
  template:
    src: sudoers.d/luksctl_api.j2
    dest: /etc/sudoers.d/luksctl_api

- name: Configure luksctl_api
  command: "{{ pyluks_venv }}/bin/luksctl_api --ssl --daemons {{ daemons | join(' ') }} --env-path {{ pyluks_venv }}"

- name: Start and enable luksctl_api for master node
  service:
    name: luksctl-api
    state: reloaded 
    enabled: yes
