---
- name: Enable luksctl_api user to run luksctl
  lineinfile:
    dest: '/etc/sudoers'
    line: 'luksctl_api ALL=NOPASSWD:{{ pyluks_venv }}/bin/luksctl'
    state: present
    insertafter: EOF

- name: '[EL] Enable luksctl_api user to run luksctl on cluster'
  lineinfile:
    dest: '/etc/sudoers'
    line: 'luksctl_api ALL=NOPASSWD:{{ pyluks_venv }}/bin/luksctl,{{ pyluks_venv }}/bin/luksctl,/bin/systemctl restart nfs-server'
    state: present
    insertafter: EOF
  when:
    - ansible_os_family == 'RedHat'
    - infrastructure_configuration == 'cluster'

- name: '[Ubuntu] Enable luksctl_api user to run luksctl on cluster'
  lineinfile:
    dest: '/etc/sudoers'
    line: 'luksctl_api ALL=NOPASSWD:{{ pyluks_venv }}/bin/luksctl,{{ pyluks_venv }}/bin/luksctl,/bin/systemctl restart nfs-kernel-server'
    state: present
    insertafter: EOF
  when:
    - ansible_os_family == 'Debian'
    - infrastructure_configuration == 'cluster'

- name: 'Enable luksctl_api user to run luksctl for docker applications'
  lineinfile:
    dest: '/etc/sudoers'
    line: 'luksctl_api ALL=NOPASSWD:{{ pyluks_venv }}/bin/luksctl,{{ pyluks_venv }}/bin/luksctl,/bin/systemctl restart docker'
    state: present
    insertafter: EOF
  when: virtualization_type == "docker"