---
# Prerequisites installation

- name: '[EL] Install prerequisites: master node'
  yum:
    name:
      - cryptsetup-luks
      - python3
      - python3-pip
      - python3-virtualenv
    state: present
  when: ansible_os_family == 'RedHat'

- name: '[Ubuntu] Install prerequisites: master node'
  apt:
    name:
      - cryptsetup
      - python3
      - python3-pip
      - python3-virtualenv
    state: present
  when: ansible_os_family == 'Debian'

# Install pyluks in a virtualenv
- name: Verify if pyluks is installed
  stat:
    path: '{{ pyluks_venv }}'
  register: pyluks_installed

- block:
  # pip needs to be upgraded to install the python package cryptography
  #- name: Upgrade pip
  #  pip:
  #    name: pip
  #    version: '{{ pip_version }}'
  #    extra_args: --upgrade
  #    executable: pip3
  
  - name: Create venv
    pip:
      name: pip
      version: '{{ pip_version }}'
      virtualenv: '{{ pyluks_venv }}'
      virtualenv_command: python3 -m virtualenv
  
  - name: Install pyluks package
    pip:
      name: pyluks
      version: '{{ pyluks_version }}'
      virtualenv: '{{ pyluks_venv }}'
  
  when: not pyluks_installed.stat.exists
